!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 128
  - - buffer_size
    - 10000
  - - gamma
    - 0.9999
  - - learning_rate
    - 0.007202464744943781
  - - learning_starts
    - 0
  - - n_timesteps
    - 300000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=-0.7260682336855917, net_arch=[256, 256])
  - - tau
    - 0.005
  - - train_freq
    - 300
